### ISSUE TITLE
FileNotFoundError clicking in "Show damages"

### ISSUE THREAD

**Issue by adrianlzt** [frangam/artdet#1]
Following the README instructions, after uploading an image if I click on "Show damages" an error is shown in the browser and the python terminal shows this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/train/via_region_data.json'
```

I'm not sure where that file should come from.

I guess I'm missing the weights. I did not see they are pointing to https://github.com/frangam/artdet/blob/main/soon, so I guess I'm too early.

**Comment by frangam** [comment]
Thanks for bringing this up!

The error you're seeing is related to the missing file data/train/via_region_data.json, which contains the annotations for the training dataset. This file should be included when you download and prepare the dataset.

To resolve this issue, please follow these steps:

Download the Dataset:

You can download the ArtInsight Dataset from https://doi.org/10.5281/zenodo.8429815.

After downloading, place the images and the associated annotation file (via_region_data.json) in the following directory structure:

data/
    train/
        via_region_data.json
        (training images)
    val/
        (validation images)


Regarding the model weights, you can now download them from the links provided in the README:
https://huggingface.co/frangam/artdet-v0/blob/main/model-maskrcnn-tf.zip

https://huggingface.co/frangam/artdet-v0/blob/main/model-maskrcnn.h5

Once downloaded, place the weights in the model/ directory as mentioned in the instructions.
Apologies for any confusion, and thank you for your patience! Let me know if you encounter any other issues.

Best regards!
